name: Terraform deployment

on:
  workflow_run:
    workflows: ["Continuos Integration terraform workflow"]
    types:
      - completed

jobs:
  deploy-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform-version: 1.10.3
    
    - name: Terraform apply auto approve
      run: terraform apply --auto-approve
