name: Terraform deployment

on:
  push:
    branches:
      - main

jobs:
  validate-terraform:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy-config:
    runs-on: ubuntu-latest
    needs: 
      - validate-terraform
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform-version: 1.10.3
    
    - name: Terraform init
      run: terraform init
      
    - name: Terraform apply auto approve
      run: terraform apply --auto-approve
