name: Terraform deployment

on:
  push:
    branches:
      - main

jobs:
  validate-terraform:
    uses: ./ci.yml

  deploy-config:
    runs-on: ubuntu-latest
    needs: validate-terraform
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform-version: 1.10.3
    
    - name: Terraform apply auto approve
      run: terraform apply --auto-approve
