name: "Continuos Integration terraform workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/ci-cd-pipeline

env: 
  access_key: ${{secrets.AWS_ACCESS_KEY}}
  secret_key: ${{secrets.AWS_SECRET_KEY}}
  session_token: ${{secrets.AWS_SESSION_TOKEN}}
  region: ${{secrets.AWS_REGION}}

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3
      
    - name: Terraform init
      run: terraform init
    
    - name: Terraform validate
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan
