name: "Continuos Integration terraform workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/ci-cd-pipeline

env: 
  access_key: ${{vars.AWS_ACCESS_KEY}}
  secret_key: ${{vars.AWS_SECRET_KEY}}
  session_token: ${{vars.AWS_SESSION_TOKEN}}
  region: ${{vars.AWS_REGION}}

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.access_key }}
        aws-secret-access-key: ${{ env.secret_key }}
        aws-session-token: ${{ env.session_token }}
        aws-region: ${{ env.region }}
    
    - name: Set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3
      
    - name: Terraform init
      run: terraform init
    
    - name: Terraform validate
      run: terraform validate
    
    - name: Terraform plan
      run: terraform plan
